GRANT CONNECT ON DATABASE contractops TO contractops_app;
GRANT USAGE ON SCHEMA public TO contractops_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO contractops_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO contractops_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO contractops_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO contractops_app;

GRANT CONNECT ON DATABASE contractops TO contractops_worker;
GRANT USAGE ON SCHEMA public TO contractops_worker;
